document.write(
          "        <div class=\"menu\">",
          "            <div class=\"el\">",
          "                <p><a href=\"index.html?doAnimation=false\" class=\"p\">Home</a></p>",
          "                <p><a href=\"Altertum.html\" class=\"p\">Altertum</a></p>",
          "                <p><a href=\"Anfänge_symmetrische_Verschlüsselung.html\" class=\"p\">Anfänge der symmetrischen Verschlüsselung</a></p>",
          "                <p><a href=\"Ab_Mittelalter.html\" class=\"p\">Verschlüsselungen ab dem Mittelalter</a></p>",
          "                <p><a href=\"1._Weltkrieg.html\" class=\"p\">Verschlüsselungen im <br> 1. Weltkrieg</a></p>",
          "                <p><a href=\"Maschinen.html\" class=\"p\">Verschlüsselung mit Maschinen</a></p>",
          "            <div id=\"menu\">",
          "            <ul>",
          "                <li>",
          "                <p class=\"left\">Verschlüsselung im 2.Weltkrieg</p>",
          "                    <ul>",
          "                        <li><a href=\"Enigma.html\" class=\"li\">Enigma</a></li>",
          "                        <li><a href=\"weitere_deutsche_Verfahren.html\" class=\"li\">Weitere deutsche Verfahren</a></li>",
          "                        <li><a href=\"US-Verfahren.html\" class=\"li\">US-Verfahren</a></li>",
          "                    </ul>",
          "                </li>",
          "            </ul>",
          "            </div>",
          "            <div id=\"menu\">",
          "            <ul>",
          "                <li>",
          "                    <p class=\"left\">Moderne symmetrische Verschlüsselungen</p>",
          "                    <ul>",
          "                        <li><a href=\"DES.html\" class=\"li\">Data Encryption Standard</a></li>",
          "                        <li><a href=\"AES.html\" class=\"li\">Advanced Encryption Standard</a></li>",
          "                    </ul>",
          "                </li>",
          "            </ul>",
          "            </div>",
          "            <p><a href=\"Asymmetrische_Verschlüsselung.html\" class=\"p\">Asymmetrische Verschlüsselung</a></p>",
          "            <p><a href=\"impressum.html\" class=\"p\">Impressum</a></p> ",
          "            <p class=\"menuside\">Menü</p>",
          "        </div>        ",
          "    </div>"
    )